server.port=8080
spring.application.name=ewm-main-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://main-db:5432/main-db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
services.statistics-service.url=http://stats-server:9090
management.endpoints.web.exposure.include=health,info